### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by mikebutts** [chiappet/prj-rev-bwfs-dasmoto#4]
Meets Expectations

Great job on this, it looks similar to the spec! The only issue I left that needs attention is using the span tag over the "p" tag. Other than that everything is great, very neat code, proper use of elements, comments, great job!   Next, try to spice up the page, maybe add a background image for the header or some colors to the divs. Coolors.co has some cool schemes you can check out. Another idea is centering the image and text so it's not all left aligned.

**Comment by chiappet** [comment]
Thanks so much! I was a little stuck on the span tag. Adding it into the "p" tag makes much more sense. Also, Coolors.co is awesome.

**Comment by chiappet** [comment]
One last thing, I made the changes you suggested. Am I supposed to resubmit? Or that's just for my edification? Also, is it okay that I'm closing out the other issues? I've never used GitHub before and I'm a little lost. Sorry!
